name: Run the script

on:
  workflow_dispatch:
  schedule:
      - cron: '0 10 * * 5'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install python-dotenv
        python -m pip install .
    - name: run the script
      run: |
        python ./src/meal_planner/main.py
      env:
        NOTIFICATION_MAILBOX: ${{ secrets.NOTIFICATION_MAILBOX }}
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        PERSONAL_MAILBOX: ${{ secrets.PERSONAL_MAILBOX }}
        MEALS_SHEET: ${{ secrets.MEALS_SHEET }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}